micronaut:
  application:
    name: pokedex
netty:
  default:
    allocator:
      max-order: 3

restApi:
  pokemon: https://pokeapi.co/api/v2/pokemon/
  species: https://pokeapi.co/api/v2/pokemon-species/
