micronaut:
  application:
    name: pokedex
netty:
  default:
    allocator:
      max-order: 3

restApi:
  pokemon: https://pokeapi.co/api/v2/pokemon/
  shakespeare: https://api.funtranslations.com/translate/shakespeare
  yoda: https://api.funtranslations.com/translate/yoda
